const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
async function run() {
  await fs.mkdir('test-results', { recursive: true });
  const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
  const application = await electron.launch(process.env.STILL_TEST_EXECUTABLE ? { executablePath: path.resolve(process.env.STILL_TEST_EXECUTABLE), args: ['--demo', '--test'], env } : { args: ['.', '--demo', '--test'], env });
  const window = await application.firstWindow(), errors = [];
  window.on('pageerror', error => errors.push(error.message));
  window.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
  try {
    await window.waitForFunction(() => typeof alerts !== 'undefined' && document.querySelector('#alert-add').onclick);
    await window.locator('[data-page="alerts"]').click();
    await window.locator('#alert-add').click();
    await window.locator('#alert-title').fill('Write the first chapter');
    await window.locator('#alert-note').fill('A small beginning is all it takes.');
    await window.locator('#alert-repeat').selectOption('weekdays');
    await window.locator('#alert-snooze-limit').fill('2');
    await window.locator('#alert-show-dismiss').selectOption('hide');
    await window.locator('#alert-block').selectOption('custom');
    await window.locator('#alert-copy-apps').click();
    await window.locator('[data-alert-app]').first().uncheck();
    const customPaths = await window.locator('[data-alert-app]:checked').evaluateAll(inputs => inputs.map(input => input.dataset.alertApp));
    assert.equal(customPaths.length, 2);
    await window.locator('#alert-dialog').evaluate(el => { el.scrollTop = 0; });
    await window.screenshot({ path: 'test-results/alert-editor.png' });
    await window.locator('#alert-save').click();
    await window.waitForSelector('#alert-dialog:not([open])', { state: 'attached' });
    let saved = await window.evaluate(() => window.still.listAlerts());
    assert.equal(saved.length, 1); assert.deepEqual(saved[0].apps.map(a => a.path), customPaths);
    assert.equal(saved[0].snoozeLimit, 2); assert.equal(saved[0].showDismiss, false);
    await window.evaluate(() => {
      const original = { ...state };
      try {
        applyStatus({ ...state, demo: false, installed: true, unavailable: false, scheduledAlerts: true, snoozeAlerts: false });
        if (document.querySelector('#alert-protection-warning').hidden) throw Error('Old guard must show preparation warning');
        applyStatus({ ...state, snoozeAlerts: true });
        if (!document.querySelector('#alert-protection-warning').hidden) throw Error('Guard upgrade must clear preparation warning immediately');
        applyStatus({ ...state, snoozeAlerts: false });
        if (document.querySelector('#alert-protection-warning').hidden) throw Error('Capability loss must restore preparation warning');
      } finally { applyStatus(original); }
    });
    assert.equal((await window.evaluate(() => window.still.status())).installed, true, 'saving a blocking alert prepares protection');
    const id = saved[0].id;
    await window.reload(); await window.waitForFunction(() => typeof alerts !== 'undefined' && alerts.length === 1);
    await window.locator('[data-page="alerts"]').click();
    await window.locator('[data-alert-toggle]').uncheck({ force: true });
    await window.waitForFunction(() => !alerts[0].enabled);
    await window.locator('[data-alert-toggle]').check({ force: true });
    await window.waitForFunction(() => alerts[0].enabled);
    await window.locator('[data-alert-edit]').click();
    // Import an image using the real copy/protocol code, substituting only the OS picker.
    const fixture = path.resolve('assets/still.png');
    await application.evaluate(({ dialog }, fixture) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [fixture] }); }, fixture);
    await window.locator('#alert-banner-pick').click();
    await window.waitForFunction(() => document.querySelector('#alert-preview-media img')?.naturalWidth > 0);
    const asset = await window.evaluate(() => alertBanner);
    assert.notEqual(asset.file, 'still.png');
    // A one-second, solid-sage VP8 fixture exercises streaming imported video.
    const videoPath = path.resolve('tests/fixtures/alert-banner.webm');
    await application.evaluate(({ dialog }, fixture) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [fixture] }); }, videoPath);
    await window.locator('#alert-banner-pick').click();
    await window.waitForFunction(() => document.querySelector('#alert-preview-media video')?.videoWidth > 0);
    await application.evaluate(({ dialog }, fixture) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [fixture] }); }, fixture);
    await window.locator('#alert-banner-pick').click();
    await window.waitForFunction(() => document.querySelector('#alert-preview-media img')?.naturalWidth > 0);
    // Import a real WAV and verify that the isolated media route can decode it.
    const wav = Buffer.alloc(44 + 8000 * 2); wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(8000, 24); wav.writeUInt32LE(16000, 28); wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(16000, 40);
    const soundPath = path.resolve('test-results/alert-fixture.wav'); await fs.writeFile(soundPath, wav);
    await application.evaluate(({ dialog }, fixture) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [fixture] }); }, soundPath);
    await window.locator('#alert-sound').selectOption('custom'); await window.locator('#alert-sound-pick').click();
    await window.waitForFunction(() => alertSoundFile !== null);
    assert.ok(await window.evaluate(() => new Promise((resolve, reject) => { const audio = new Audio('still-media://local/' + alertSoundFile.file); audio.onloadedmetadata = () => resolve(audio.duration); audio.onerror = () => reject(Error('WAV did not decode')); })));
    await window.locator('#alert-listen').click(); await window.locator('#alert-listen').click();
    await window.locator('#alert-sound').selectOption('bell');
    await window.locator('#alert-listen').click();
    await window.locator('#alert-listen').click();
    const [card] = await Promise.all([application.waitForEvent('window'), window.locator('#alert-preview').click()]);
    await card.waitForSelector('#alarm-title:has-text("Write the first chapter")');
    assert.equal(await card.evaluate(() => window.still), undefined, 'alarm has no blocking IPC');
    await card.waitForFunction(() => document.querySelector('.alarm-media img')?.naturalWidth > 0);
    const topmost = await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().filter(w => w.webContents.getURL().endsWith('/alarm.html')).every(w => w.isAlwaysOnTop()));
    assert.equal(topmost, true);
    await card.screenshot({ path: 'test-results/alert-card.png' });
    await card.locator('#alarm-dismiss').click();
    await window.locator('[name="alert-style"][value="full"]').check();
    const [full] = await Promise.all([application.waitForEvent('window'), window.locator('#alert-preview').click()]);
    await full.waitForSelector('body.alarm-full');
    assert.equal(await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().filter(w => w.webContents.getURL().endsWith('/alarm.html')).every(w => w.isFullScreen())), true);
    await full.locator('#alarm-dismiss-top').click();
    await window.locator('[name="alert-style"][value="notification"]').check();
    assert.equal(await window.locator('#alert-banner-controls').isHidden(), true);
    await window.locator('#alert-sound').selectOption('silent');
    await window.locator('#alert-preview').click();
    assert.equal(await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().filter(w => w.webContents.getURL().endsWith('/alarm.html')).length), 0, 'silent notification needs no renderer');
    await window.waitForTimeout(10200); // Keep the native notification's existing presentation lifetime.
    await window.locator('#alert-save').click();
    await window.waitForSelector('#alert-dialog:not([open])', { state: 'attached' });
    await window.screenshot({ path: 'test-results/alerts-list.png', fullPage: true });
    // Drive a due alert through the production scheduler while main UI is hidden.
    await window.evaluate(async () => { await window.still.install(); await window.still.deleteAlert(alerts[0].id); });
    const record = await window.evaluate(async () => {
      const now = new Date();
      return (await window.still.saveAlert({ title: 'Scheduled focus', note: '', date: alertDateString(now), time: alertTimeString(now), repeat: 'once', lengthMode: 'duration', durationMinutes: 2, endTime: '23:59', style: 'card', blockMode: 'current', apps: [], unlockDelayMinutes: 0, sound: 'silent', volume: 65, enabled: true, snoozeLimit: 1, showDismiss: false }))[0];
    });
    await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/index.html')).hide());
    await window.waitForFunction(() => state.session?.intention === 'Scheduled focus', null, { polling: 100, timeout: 15000 });
    const session = await window.evaluate(() => window.still.status());
    const expected = new Date(record.date + 'T' + record.time + ':00').getTime() + 120000;
    assert.equal(session.session.endsAt, expected, 'exact deadline retained, including for short remaining windows');
    assert.equal(session.session.apps.length, 3, 'dynamic selection uses persisted Focus space apps');
    const alarm = application.windows().find(w => w !== window && w.url().endsWith('/alarm.html'));
    await window.waitForFunction(() => alerts[0]?.ringing, null, { polling: 100 });
    await alarm.waitForSelector('#alarm-snooze');
    assert.equal(await alarm.locator('#alarm-dismiss').isHidden(), true);
    assert.equal(await alarm.locator('#alarm-dismiss-top').isHidden(), true);
    await alarm.locator('#alarm-snooze').click();
    saved = await window.evaluate(() => window.still.listAlerts()); assert.ok(saved[0].snoozeAt > Date.now());
    assert.equal(saved[0].nextAt, saved[0].snoozeAt, 'snoozed one-time alert is upcoming');
    await window.evaluate(() => window.still.showWindow());
    await window.waitForSelector('.alert-row.snoozed .alert-status:has-text("Snoozed · alerts again")', { state: 'attached' });
    assert.equal(await window.locator('.alert-status').innerText(), await window.evaluate(time => 'Snoozed · alerts again ' + alertWhen(time), saved[0].snoozeAt));
    assert.match(await window.locator('#alert-next-detail').innerText(), /Snoozed/);
    await window.evaluate(() => window.still.showWindow());
    await window.screenshot({ path: 'test-results/alerts-snoozed.png', fullPage: true });
    await window.reload();
    await window.waitForFunction(() => typeof alerts !== 'undefined' && alerts[0]?.snoozeAt);
    await window.locator('[data-page="alerts"]').click();
    assert.match(await window.locator('.alert-status').innerText(), /Snoozed/);
    assert.equal((await window.evaluate(() => window.still.status())).session, null, 'snoozing unblocks apps');
    await window.evaluate(() => window.still.start({ apps: [{ name: 'Game', path: 'C:\\StillPreview\\Game.exe' }], intention: 'Scheduled focus', durationMinutes: 2, unlockDelayMinutes: 0 }));
    await window.evaluate(async () => { const first = alerts[0]; await window.still.saveAlert({ ...first, id: undefined, title: 'Overlapping focus', blockMode: 'custom', apps: [{ name: 'Minecraft', path: 'C:\\StillPreview\\Minecraft.exe' }] }); });
    await window.waitForFunction(() => alerts.some(a => a.title === 'Overlapping focus' && a.lastResult.includes('Another focus session')), null, { polling: 100 });
    assert.equal((await window.evaluate(() => window.still.status())).session.intention, 'Scheduled focus');
    await window.evaluate(() => window.still.end());
    await window.waitForFunction(() => state.session?.intention === 'Overlapping focus', null, { polling: 100 });
    const overlapping = (await window.evaluate(() => window.still.status())).session;
    assert.equal(overlapping.endsAt, expected); assert.equal(overlapping.apps.length, 1);
    await window.evaluate(async () => { await window.still.end(); for (const a of await window.still.listAlerts()) await window.still.deleteAlert(a.id); await window.still.showWindow(); });
    await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1000, 760));
    await window.locator('#alert-add').click();
    assert.equal(await window.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.equal(await window.locator('#alert-dialog').evaluate(el => el.scrollWidth > el.clientWidth), false);
    await window.screenshot({ path: 'test-results/alert-editor-compact.png' });
    assert.deepEqual(errors, []);
    console.log('PASS: alert editor, app overrides, persistence, pause, imported banner, alarm previews, fullscreen/topmost windows, exact scheduled blocking in tray, snooze and compact layout.');
  } finally { await application.close(); }
}
run().catch(error => { console.error(error); process.exitCode = 1; });
