const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');

async function run() {
  const environment = { ...process.env }; delete environment.ELECTRON_RUN_AS_NODE;
  const packaged = process.argv.includes('--packaged');
  const app = await electron.launch({ ...(packaged ? { executablePath: path.resolve('release/win-unpacked/Still.exe') } : {}), args: [...(packaged ? [] : ['.']), '--demo', '--test'], env: environment });
  try {
    const page = await app.firstWindow(), errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    await page.waitForSelector('#preview-banner:not([hidden])');
    await page.locator('[data-page=todos]').click();
    const lines = page.locator('.todo-input');
    await lines.first().fill('Write the outline /circle');
    assert.equal(await page.getByRole('option').count(), 1);
    await lines.first().press('Enter');
    assert.equal(await lines.first().inputValue(), 'Write the outline ');
    assert.equal(await page.locator('.todo-check.circle').count(), 1);
    await lines.first().press('Enter');
    await lines.nth(1).fill('/heading');
    await page.getByRole('option', { name: /Heading/ }).click();
    await lines.nth(1).fill('For later');
    await lines.nth(1).press('End');
    await lines.nth(1).press('Enter');
    assert.equal(await page.locator('.todo-row.checkbox').count(), 1, 'Heading continues into a task');
    await lines.nth(2).fill('/');
    assert.equal(await page.getByRole('option').count(), 6);
    await lines.nth(2).press('ArrowDown');
    await lines.nth(2).press('ArrowDown');
    await lines.nth(2).press('Enter');
    await lines.nth(2).fill('A useful idea');
    assert.equal(await page.locator('.todo-row.bullet').count(), 1);
    for (const format of ['number', 'note', 'checkbox']) {
      await page.locator('#todo-add').click();
      await lines.last().fill('/' + format);
      await lines.last().press('Enter');
      await lines.last().fill(format === 'checkbox' ? '<img src=x onerror=alert(1)>' : format + ' text');
    }
    await page.locator('[data-todo-check]').first().click();
    assert.equal(await page.locator('#todo-progress').innerText(), '1 OF 2 COMPLETE');
    await lines.last().fill('Keep /unknown');
    assert.equal(await page.getByRole('option').count(), 0);
    await lines.last().press('Escape');
    assert.equal(await lines.last().inputValue(), 'Keep /unknown');
    await lines.last().fill('<img src=x onerror=alert(1)>');
    await page.waitForFunction(() => document.querySelector('#todo-save-status').textContent === 'Saved on this PC');
    const saved = await page.evaluate(async () => (await window.still.bootstrap()).preferences.todos);
    assert.equal(saved.length, 6);
    await page.reload();
    await page.waitForSelector('#preview-banner:not([hidden])');
    await page.locator('[data-page=todos]').click();
    assert.equal(await lines.count(), 6);
    assert.equal(await page.locator('[data-todo-check]').first().getAttribute('aria-checked'), 'true');
    assert.equal(await lines.last().inputValue(), '<img src=x onerror=alert(1)>');
    assert.equal(await page.locator('#todo-rows img').count(), 0, 'List text is never interpreted as HTML');
    await page.locator('#todo-add').click();
    await lines.last().press('Backspace');
    assert.equal(await lines.count(), 6);
    await page.locator('[data-todo-delete]').last().click();
    assert.equal(await lines.count(), 5);
    const texts = () => lines.evaluateAll(inputs => inputs.map(input => input.value));
    const original = await texts();
    const box = await lines.first().boundingBox();
    await page.mouse.move(box.x + 20, box.y + box.height / 2); await page.mouse.down();
    await page.waitForTimeout(700); await page.mouse.up();
    assert.equal(await page.locator('#todo-select-bar').isVisible(), true, 'Holding a line enters selection mode');
    assert.equal(await page.locator('#todo-select-count').innerText(), '1 SELECTED', 'The held line is selected and the release click does not unselect it');
    assert.equal(await page.locator('[data-todo-handle]').count(), 5);
    assert.equal(await page.locator('#todo-add').isVisible(), false);
    await lines.nth(2).click({ force: true });
    assert.equal(await page.locator('#todo-select-count').innerText(), '2 SELECTED');
    await page.locator('#todo-select-all').click();
    assert.equal(await page.locator('#todo-select-count').innerText(), '5 SELECTED');
    await page.locator('#todo-select-all').click();
    assert.equal(await page.locator('#todo-select-delete').isDisabled(), true);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#todo-select-bar').isVisible(), false);
    assert.equal(await page.locator('[data-todo-handle]').count(), 0);
    await lines.first().click({ button: 'right' });
    await page.locator('[data-todo-handle]').first().press('ArrowDown');
    assert.deepEqual(await texts(), [original[1], original[0], ...original.slice(2)], 'Arrow keys move a line');
    const from = await page.locator('[data-todo-handle]').last().boundingBox(), to = await lines.first().boundingBox();
    await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2); await page.mouse.down();
    await page.mouse.move(from.x + from.width / 2, to.y + 4, { steps: 12 }); await page.mouse.up();
    const moved = [original[4], original[1], original[0], original[2], original[3]];
    assert.deepEqual(await texts(), moved, 'Dragging the handle moves a line');
    await page.locator('#todo-select-cancel').click();
    await lines.nth(1).click({ button: 'right' });
    await lines.nth(3).click({ force: true });
    await page.locator('#todo-select-delete').click();
    assert.deepEqual(await texts(), [moved[0], moved[2], moved[4]]);
    assert.equal(await page.locator('#todo-select-bar').isVisible(), false);
    await page.locator('#todo-undo').click();
    assert.deepEqual(await texts(), moved, 'Undo puts deleted lines back in place');
    await page.waitForFunction(() => document.querySelector('#todo-save-status').textContent === 'Saved on this PC');
    assert.deepEqual((await page.evaluate(async () => (await window.still.bootstrap()).preferences.todos)).map(item => item.text), moved, 'New order is saved');
    await lines.first().click({ button: 'right' });
    await fs.mkdir('test-results', { recursive: true });
    await page.screenshot({ path: 'test-results/todos-select.png', fullPage: true });
    await page.locator('#todo-select-cancel').click();
    await fs.mkdir('test-results', { recursive: true });
    await page.screenshot({ path: 'test-results/todos.png', fullPage: true });
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1000, 760));
    await lines.last().fill('/');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.screenshot({ path: 'test-results/todos-menu.png', fullPage: true });
    assert.deepEqual(errors, [], 'No renderer or CSP errors');
    console.log('Passed: all six formats, keyboard and mouse selection, completion, safe text, local persistence, deletion, hold-to-select, bulk delete with undo, reordering, and compact layout.');
  } finally { await app.close(); }
}
run().catch(error => { console.error(error); process.exitCode = 1; });
