const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
async function run() {
  await fs.mkdir('test-results', { recursive: true });
  const environment = { ...process.env }; delete environment.ELECTRON_RUN_AS_NODE;
  const application = await electron.launch({ args: ['.', '--demo', '--test'], env: environment, timeout: 60000 });
  const window = await application.firstWindow();
  const errors = [];
  window.on('pageerror', error => errors.push(error.message));
  window.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  try {
    await window.waitForSelector('#preview-banner:not([hidden])');
    await window.waitForFunction(() => document.querySelectorAll('#selected-apps .app-row').length > 0);
    await window.evaluate(() => document.fonts.ready);
    await window.waitForTimeout(600);
    await window.screenshot({ path: 'test-results/focus-space.png', fullPage: true });
    assert.equal(await window.locator('h1').first().innerText(), 'Your time. On purpose.');
    await window.locator('#add-apps').click();
    await window.locator('#picker-search').fill('Minecraft');
    assert.equal(await window.locator('#picker-list .app-row').count(), 1);
    await window.locator('#picker-list .app-row').click();
    await window.locator('#picker-done').click();
    await window.locator('[data-page="library"]').click();
    await window.locator('#save-group').click();
    await window.locator('#group-name').fill('Deep work');
    await window.locator('#group-save').click();
    assert.ok(await window.locator('#saved-groups').innerText().then(t => t.includes('Deep work')));
    await window.locator('[data-page="focus"]').click();
    await window.locator('#duration').fill('1'); await window.locator('#duration').dispatchEvent('change');
    await window.locator('#intention').fill('One meaningful thing');
    await window.locator('#intention').dispatchEvent('change');
    await window.locator('#start-button').click();
    await window.locator('#confirm-accept').click();
    await window.waitForFunction(() => document.querySelector('#protection-status').textContent.includes('ready'));
    await window.locator('#start-button').click();
    await window.locator('#confirm-accept').click();
    await window.waitForSelector('.focus-card.running');
    assert.equal(await window.locator('#delay-enabled').isDisabled(), true);
    assert.equal(await window.locator('#choose-apps').isDisabled(), true);
    assert.equal(await window.locator('#session-setup').isHidden(), true);
    await window.locator('#start-button').click();
    await window.locator('#confirm-accept').click();
    await window.waitForSelector('#unlock-info:not([hidden])');
    assert.equal(await window.locator('#start-button').isDisabled(), true);
    const earlyRelease = await window.evaluate(async () => { try { await window.still.end(); return false; } catch { return true; } });
    assert.equal(earlyRelease, true, 'IPC rejects release before delay');
    await window.screenshot({ path: 'test-results/active-session.png', fullPage: true });
    await window.locator('#cancel-unlock').click();
    await window.waitForSelector('#unlock-info[hidden]', { state: 'attached' });
    const beforeReload = await window.evaluate(() => window.still.status());
    await window.reload();
    await window.waitForSelector('.focus-card.running');
    const afterReload = await window.evaluate(() => window.still.status());
    assert.equal(afterReload.session.endsAt, beforeReload.session.endsAt, 'Window reload preserves deadline');
    assert.equal(afterReload.session.unlockAt, 0, 'Cancelled release stays cancelled');
    await window.locator('[data-page="settings"]').click();
    assert.equal(await window.locator('#remove-guard').isDisabled(), true);
    await window.locator('#reduced-motion').check({ force: true });
    assert.equal(await window.locator('body').evaluate(el => el.classList.contains('reduced-motion')), true);
    await window.screenshot({ path: 'test-results/settings.png', fullPage: true });
    await window.locator('[data-page="focus"]').click();
    await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1000, 760));
    await window.screenshot({ path: 'test-results/compact.png', fullPage: true });
    const overflowing = await window.evaluate(() => document.documentElement.scrollWidth > innerWidth);
    assert.equal(overflowing, false, 'No horizontal overflow at minimum window width');
    // Natural expiry is tested against the running timer, not by mutating app internals.
    await window.waitForSelector('.focus-card:not(.running)', { timeout: 70000 });
    await window.locator('[data-page="history"]').click();
    assert.equal(await window.locator('#total-completed').innerText(), '1');
    assert.ok((await window.locator('#history-list').innerText()).includes('One meaningful thing'));
    await window.screenshot({ path: 'test-results/history.png', fullPage: true });
    const monthLabel = await window.locator('#calendar-month').innerText();
    assert.equal(await window.locator('.calendar-day.has-session').count(), 1);
    assert.equal(await window.locator('.calendar-weekday').count(), 7);
    const calendarBox = await window.locator('.session-calendar').boundingBox();
    assert.ok(calendarBox.width <= 350 && calendarBox.height < 480, 'Calendar stays compact');
    await window.locator('#calendar-previous').click();
    assert.notEqual(await window.locator('#calendar-month').innerText(), monthLabel);
    assert.equal(await window.locator('.calendar-day.has-session').count(), 0);
    await window.locator('#calendar-next').click();
    assert.equal(await window.locator('#calendar-month').innerText(), monthLabel);
    assert.equal(await window.locator('.calendar-day.has-session').count(), 1);
    await window.locator('#calendar-next').click();
    assert.notEqual(await window.locator('#calendar-month').innerText(), monthLabel);
    await window.locator('#calendar-previous').click();
    const totalBefore = await window.locator('#total-time').innerText();
    await window.locator('[data-history-action="archive"]').click();
    await window.waitForFunction(() => document.querySelectorAll('.history-row').length === 0);
    assert.equal(await window.locator('#total-completed').innerText(), '1');
    assert.equal(await window.locator('#total-time').innerText(), totalBefore);
    await window.locator('#history-filter').selectOption('archived');
    assert.equal(await window.locator('.history-row').count(), 1);
    await window.locator('[data-history-action="restore"]').click();
    await window.waitForFunction(() => document.querySelectorAll('.history-row').length === 0);
    await window.locator('#history-filter').selectOption('all');
    await window.locator('#progress-days').selectOption('7');
    await window.locator('#progress-metric').selectOption('sessions');
    await window.locator('#daily-goal').fill('25');
    await window.locator('#daily-goal').dispatchEvent('change');
    await window.waitForFunction(async () => (await window.still.bootstrap()).preferences.dailyGoal === 25);
    await window.reload();
    await window.locator('[data-page="history"]').click();
    assert.equal(await window.locator('#daily-goal').inputValue(), '25');
    assert.equal(await window.locator('.trend-bar').count(), 7);
    await window.locator('[data-history-action="delete"]').click();
    await window.locator('#confirm-cancel').click();
    assert.equal(await window.locator('.history-row').count(), 1);
    await window.locator('[data-history-action="delete"]').click();
    await window.locator('#confirm-accept').click();
    await window.waitForFunction(() => document.querySelector('#total-completed').textContent === '0');
    assert.equal(await window.locator('#total-time').innerText(), '0m');
    assert.equal(await window.locator('.calendar-day.has-session').count(), 0);
    assert.equal((await window.evaluate(() => window.still.status())).history.length, 0);
    assert.equal(await window.locator('.history-row').count(), 0);
    assert.equal(await window.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.deepEqual(errors, [], 'No renderer or CSP errors');
    console.log('Passed: app picker, saved groups, protection setup, session start, locked settings, delayed release rejection, cancellation, reload persistence, reduced motion, compact layout, natural expiry, and history.');
  } finally { await application.close(); }
}
run().catch(error => { console.error(error); process.exitCode = 1; });
