const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
async function run() {
  await fs.mkdir('test-results', { recursive: true });
  const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
  const application = await electron.launch({ ...(process.env.STILL_TEST_EXECUTABLE ? { executablePath: path.resolve(process.env.STILL_TEST_EXECUTABLE), args: ['--demo', '--test'] } : { args: ['.', '--demo', '--test'] }), env, timeout: 60000 });
  const window = await application.firstWindow(), errors = [];
  window.on('pageerror', error => errors.push(error.message));
  try {
    await window.waitForSelector('#selected-apps .app-row');
    await window.locator('#choose-apps').click();
    while (await window.locator('#picker-list [aria-checked="true"]').count()) await window.locator('#picker-list [aria-checked="true"]').first().click();
    await window.locator('#picker-website-address').fill('https://www.youtube.com/watch?v=123');
    await window.locator('#picker-website-add').click();
    await window.locator('[data-picker-kind="websites"]').click();
    assert.equal(await window.locator('#picker-list .app-row').count(), 1);
    assert.match(await window.locator('#picker-count').innerText(), /1 apps \/ websites/);
    await window.screenshot({ path: 'test-results/website-picker.png' });
    await window.locator('#picker-done').click();
    await window.locator('[data-page="library"]').click();
    await window.locator('#save-group').click(); await window.locator('#group-name').fill('Quiet web'); await window.locator('#group-save').click();
    await window.locator('[data-page="settings"]').click();
    await window.locator('[name="website-screen"][value="custom"]').check({ force: true });
    await window.locator('#website-screen-title').fill('<Keep going>'); await window.locator('#website-screen-title').blur();
    await window.locator('#website-screen-text').fill('A page at a time.'); await window.locator('#website-screen-text').blur();
    assert.equal(await window.locator('#website-preview-title').innerText(), '<Keep going>');
    assert.equal(await window.locator('#website-preview-title *').count(), 0, 'Text is never interpreted as HTML');
    await application.evaluate(({ dialog }, fixture) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [fixture] }); }, path.resolve('assets/still.png'));
    await window.locator('#website-image-pick').click();
    await window.waitForFunction(() => document.querySelector('#website-preview-image').naturalWidth > 0);
    assert.ok(await window.evaluate(() => prefs.blockScreen.image.length <= 180000));
    await window.locator('[name="website-screen"][value="redirect"]').check({ force: true });
    await window.locator('#website-redirect').fill('https://m.youtube.com/'); await window.locator('#website-redirect').blur();
    assert.match(await window.locator('#website-screen-error').innerText(), /outside/);
    await window.locator('#website-redirect').fill('https://example.com/notes'); await window.locator('#website-redirect').blur();
    assert.equal(await window.locator('#website-screen-error').innerText(), '');
    await window.locator('[name="website-screen"][value="dusk"]').check({ force: true });
    await window.locator('.website-settings').scrollIntoViewIfNeeded();
    await window.screenshot({ path: 'test-results/website-screens.png', fullPage: true });
    await window.locator('[data-page="limits"]').click();
    assert.equal(await window.locator('[data-limit-website]').count(), 5, 'Five recommended websites');
    await window.locator('[data-limit-website="youtube.com"]').click();
    await window.locator('#limit-address').fill('https://www.twitch.tv/directory'); await window.locator('#limit-address').press('Enter');
    await window.locator('[data-domain="youtube.com"] [data-limit-minutes]').selectOption('60');
    await window.locator('[data-domain="twitch.tv"] [data-limit-bedtime]').uncheck();
    await window.locator('#bedtime-from').fill('23:15'); await window.locator('#bedtime-from').dispatchEvent('change');
    assert.equal(await window.locator('[data-limit-website]').count(), 4);
    await window.locator('.website-limits').scrollIntoViewIfNeeded();
    await window.locator('.website-limits').screenshot({ path: 'test-results/website-limits.png' });
    await window.locator('[data-page="alerts"]').click(); await window.locator('#alert-add').click();
    await window.locator('#alert-title').fill('Read without feeds');
    await window.locator('#alert-block').selectOption('custom');
    await window.locator('#alert-website-address').fill('reddit.com'); await window.locator('#alert-website-add').click();
    await window.locator('#alert-save').click();
    await window.waitForSelector('#alert-dialog:not([open])', { state: 'attached' });
    const alerts = await window.evaluate(() => window.still.listAlerts());
    assert.deepEqual(alerts[0].apps, [{ name: 'reddit.com', path: 'website:reddit.com' }]);
    await window.evaluate(() => saveQueue);
    await window.reload(); await window.waitForSelector('#selected-apps [data-app="website:youtube.com"]');
    assert.equal(await window.evaluate(() => prefs.blockScreen.mode), 'dusk');
    assert.deepEqual(await window.evaluate(() => prefs.websiteLimits), { bedtime: { from: '23:15', to: '07:00' }, sites: [{ domain: 'youtube.com', minutes: 60, bedtime: true }, { domain: 'twitch.tv', minutes: 30, bedtime: false }] });
    assert.equal(await window.evaluate(() => groups[0].paths[0]), 'website:youtube.com');
    await window.locator('#delay-enabled').uncheck();
    await window.locator('#start-button').click(); await window.locator('#confirm-accept').click();
    await window.waitForSelector('.focus-card.running');
    const session = await window.evaluate(() => window.still.status());
    assert.equal(session.session.apps.length, 1); assert.equal(session.session.blockScreen.mode, 'dusk');
    await window.locator('[data-page="settings"]').click();
    assert.equal(await window.locator('[name="website-screen"]').first().isDisabled(), true);
    await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1000, 760));
    assert.equal(await window.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await window.locator('[data-page="focus"]').click(); await window.locator('#start-button').click(); await window.locator('#confirm-accept').click();
    await window.waitForSelector('.focus-card:not(.running)');
    assert.equal((await window.evaluate(() => window.still.status())).history[0].apps[0].path, 'website:youtube.com');
    assert.deepEqual(errors, []);
    console.log('Website UI passed: selection, groups, scheduled selection, presets, custom text, daily limits and bedtime, redirect validation, persistence, website-only sessions, locking and compact layout.');
  } finally { await application.close(); }
}
run().catch(error => { console.error(error); process.exit(1); });
